# Generated by Django 6.0.4 on 2026-05-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('num_tel_client', models.CharField(max_length=20)),
                ('email_client', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=100)),
                ('prenom_employe', models.CharField(max_length=100)),
                ('num_tel_employe', models.CharField(max_length=20)),
                ('specialisation', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
                ('grade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employe',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('type_abonnement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Entreprise',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Notification Push')], max_length=20)),
                ('message', models.TextField()),
                ('date_envoie', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prestation', models.CharField(max_length=200)),
                ('duree_prestation', models.IntegerField(help_text='Durée en minutes')),
                ('prix', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('employes', models.ManyToManyField(blank=True, to='gestion.employe')),
            ],
            options={
                'db_table': 'Prestation',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserver', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('avis', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employe')),
                ('prestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.prestation')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('methode_de_paiement', models.CharField(choices=[('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('mobile', 'Mobile Money')], max_length=20)),
                ('date_de_paiement', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.reservation')),
            ],
            options={
                'db_table': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salon', models.CharField(max_length=200)),
                ('adresse_salon', models.CharField(max_length=300)),
                ('num_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateField()),
                ('nom_gerant', models.CharField(max_length=100)),
                ('horaire_ouverture', models.TimeField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
            options={
                'db_table': 'Salon',
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.salon'),
        ),
        migrations.AddField(
            model_name='employe',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.salon'),
        ),
    ]
